### ISSUE TITLE
Maintenance release: v3.2

### ISSUE THREAD

**Issue by smmaurer** [UDST/urbansim#218]
This issue is to plan a maintenance release for the `urbansim` library. 

The current release is v3.1.1 and the new one will be v3.2. I'd like to include as many pending bug fixes and compatibility updates as possible, without making any changes that would be backwards-incompatible. 

As a heads-up, aspects of this library’s functionality have been replaced by other more targeted packages, which are where additional feature development is most likely to occur:

- task orchestration is now handled by [Orca](https://github.com/UDST/orca)
- real estate development logic is now in [Developer](https://github.com/UDST/developer)
- discrete choice logic is now in [ChoiceModels](https://github.com/UDST/choicemodels)
- reusable model step patterns are in [UrbanSim Templates](https://github.com/UDST/urbansim_templates)

### Previously merged PR’s

These PR’s have been merged to the master branch subsequent to v3.1.1, and will be included in this release:

- PR #198 (support for exporting ordered dicts to yaml)
- PR #200 (bug fix in transition model error checking)
- PR #201 (temporarily pins Pandana at v0.3)
- PR #211 (warns if logit estimation may not have converged)

### Compatibility updates

Additional updates that i think should be included in this release:

- [x] resolve deprecation warnings (issues #215, #216)
- [x] resolve dependency incompatibilities (issues #169, #214, #217)
- [x] streamline CI tests and include more recent Python versions
- [x] enable distribution on conda-forge (involves issue #203)

### Before finalizing

- [x] update documentation and wiki
- [x] update version numbers

Anything else we should consider including?

**Comment by smmaurer** [comment]
Completed. See PRs #225, #226, #227.
